### ISSUE TITLE
405 Not Allowed  - Jetbrain Intellij

### ISSUE THREAD

**Issue by Samuel-Oliveira** [wakatime/jetbrains-wakatime#112]
Hi Guys!
After a day of work, I went to check my hours and to my sadness nothing was recorded. I enabled the log and I noticed the messages:

https://pastebin.com/3aezsq5h

so, two questions.... i lost all my progress today? How to correct this.

**Comment by alanhamlett** [comment]
That error in your log file is a normal networking error when sending some coding activity, but that data is safely stored in sqlite3 locally until it can be successfully synced. Syncing happens when you're coding, or you can force all offline coding activity to sync with this command:
https://github.com/wakatime/wakatime/issues/157#issuecomment-444993029

**Comment by Samuel-Oliveira** [comment]
Thank you!
