### ISSUE TITLE
Opensource?

### ISSUE THREAD

**Issue by gringofe** [wakatime/jetbrains-wakatime#139]
Hello,

your plugins are being advertised as "open source", however, I can't find the server code anywhere? 
What's the use of the plugin being open source when your servercode, where all the data is sent to, is not auditable? How can I be sure that you don't sell/analyze this data? Why can't people self host?

Regards

**Comment by alanhamlett** [comment]
Here's the data the server collects from plugins:
https://wakatime.com/faq#data-collected

You can be sure we don't sell user data because that's a violation of our privacy policy:
https://wakatime.com/privacy

We're based in California, so existing privacy laws require we publish how we use your PII:
https://en.wikipedia.org/wiki/Online_Privacy_Protection_Act

We don't sell any user PII, even scrubbed. We make all revenue from paid subscriptions seen here:
https://wakatime.com/pricing

We're open to letting a third party audit the server code if that makes sense.
