### ISSUE TITLE
Upgrade the WakaTime CLI

### ISSUE THREAD

**Issue by Olegt0rr** [wakatime/jetbrains-wakatime#163]
Upgrade the WakaTime CLI via restarting PyCharm is not working.

#### PyCharm version
```
PyCharm 2020.3.4 (Professional Edition)
Build #PY-203.7717.65, built on March 16, 2021
Runtime version: 11.0.10+8-b1145.96 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 10.16
GC: ParNew, ConcurrentMarkSweep
Memory: 990M
Cores: 4
Registry: ide.balloon.shadow.size=0
Non-Bundled Plugins: Pomodoro-tm, Rider UI Theme Pack, YAML/Ansible support, Activity Tracker, ru.yandex.tracker, com.samdark.intellij-visual-studio-code-dark-plus, com.wakatime.intellij.plugin, de.docs_as_co.intellij.plugin.diagramsnet, ideanginx9, com.failfast, com.almightyalpaca.intellij.plugins.discord, mobi.hsz.idea.gitignore, name.kropp.intellij.makefile, com.intellij.kubernetes, org.toml.lang, org.intellij.tasks.navigation, com.jetbrains.intellij.datalore, com.koxudaxi.poetry, com.koxudaxi.pydantic, ru.adelf.idea.dotenv, ru.meanmail.plugin.requirements
```

<img width="813" alt="Screenshot 2021-03-23 at 17 19 45" src="https://user-images.githubusercontent.com/25399456/112161230-fe093300-8bfb-11eb-96e3-11616e07500e.png">

**Comment by alanhamlett** [comment]
We switched to a standalone compiled version of wakatime-cli, but we're now working on a brand new Go version since compiling Python isn't maintainable in the long run. You're on the latest wakatime-cli source version, so everything is ok. We'll skip the standalone version and go straight to the Go wakatime-cli soon to fix this.
