### ISSUE TITLE
Time suddenly missing from 28/10/2021 to 05/11/2021

### ISSUE THREAD

**Issue by fessak** [wakatime/jetbrains-wakatime#192]
Yesterday, everything was normal. The data was coming through and I could see the time in my Dashboard, specifically the project "Projeto_04_parrotsCardGame". But today, when I logged on, suddenly, everything I did from 28/10/2021 to 05/11/2021 disappeared. 
I searched google and found this link <https://githubmemory.com/repo/wakatime/vscode-wakatime/issues/232> which looked like the same issue.
I did what user "alanhamlett" suggested and it revived my wakatime puglin inside vs code (which you can notice 7 minutes spent in the "Projeto_04_parrotsCardGame" project), but the time lost didn't return... What should I do?

**Comment by alanhamlett** [comment]
It looks like code stats from this error are lost, because `wakatime-cli` exits without saving the heartbeat to the offline db:
https://github.com/wakatime/wakatime-cli/blob/61dac3bcc6671dd54f787ec466bf115c504b51f9/cmd/legacy/run.go#L43

However, there will be a log of the file you were editing along with the timestamps in `~/.wakatime.log`. If you email that log file to `support@wakatime.com` we can help recover that lost time for you.

**Comment by fessak** [comment]
Hello!
Thank you very much! I will e-mail them my log right away. Also, how can I lock the config files?

**Comment by alanhamlett** [comment]
Locking the config files is something the wakatime-cli program might do in the future, but it can't be done manually.

**Comment by alanhamlett** [comment]
Unfortunately, this coding activity is lost since wakatime-cli exits without logging any error message to the log file whenever it's unable to read the config file.

I've opened two issues on the wakatime-cli repo to fix this.

**Comment by fessak** [comment]
No problem! 
I wonder if the issue has anything to do with a bad internet connection? Mine has been acting up these days...
Again, thank you for your attention. Great service!
