### ISSUE TITLE
Find a way to include python binary in this

### ISSUE THREAD

**Issue by func0der** [wakatime/jetbrains-wakatime#29]
Relying on external dependencies is not that nice. Please try to include the needed python binary(-ies) in this plugin or maybe re-write the implementation in Java.

**Comment by alanhamlett** [comment]
Rewriting is not an option, because the point of [wakatime cli](https://github.com/wakatime/wakatime) is to implement common functions once and reuse in every plugin, no matter what language that plugin is written in.


Do you mean wakatime cli or the dependency on python itself at [Dependencies.java#L173](https://github.com/wakatime/jetbrains-wakatime/blob/4284f79bdd18e52361d9622e6010a68c199be698/src/com/wakatime/intellij/plugin/Dependencies.java#L173)?

**Comment by alanhamlett** [comment]
Closing this since downloading Python from python.org has been working so far.
