### ISSUE TITLE
Huge CPU Load and Usage, pythonw many process

### ISSUE THREAD

**Issue by sonique6784** [wakatime/jetbrains-wakatime#68]
Hi Guys,
I've huge CPU load + usage, when wakatime send data to remote server. I can seen hundreds of the following process, with deferent file ( --file ).

`pythonw /Users/.../Library/Application Support/AndroidStudio2.1/WakaTime-resources/wakatime-master/wakatime/cli.py --file /Users/.../Documents/git/android/somefile.xml --key MY_KEY --project android --plugin AndroidStudio/2.1 AndroidStudio-wakatime/6.0.7 TMPDIR=/var/folders/ry/6trz342j74gf3zblpq7tcs8r0000gq/T/ SHELL=/bin/bash HOME=/Users/... Apple_PubSub_Socket_Render=/private/tmp/com.apple.launchd.6uTW4eVTQ3/Render SSH_AUTH_SOCK=/private/tmp/com.apple.launchd.Qil02eutEc/Listeners LOGNAME=... PATH=/usr/bin:/bin:/usr/sbin:/sbin XPC_SERVICE_NAME=com.apple.xpc.launchd.oneshot.0x10000003.studio COMMAND_MODE=unix2003 USER=... SECURITYSESSIONID=186a8 XPC_FLAGS=0x0 __CF_USER_TEXT_ENCODING=0x1F7:0x0:0x0
`

**Comment by alanhamlett** [comment]
Same issue as #65. We've fixed this in Visual Studio and Sublime Text plugins already and will have a fix for Android Studio soon too. If you want to help with a PR, here's the relevant examples of the fix for other plugins:

https://github.com/wakatime/visualstudio-wakatime/commit/025a4e5fb863065889731fdea47f6d701c3c3ef5
https://github.com/wakatime/sublime-wakatime/commit/48810f2977ddefb67131b7845bd9f9095af576b4

**Comment by alanhamlett** [comment]
Fixed with c394dbbc2eb14150a126c594c3f6bc9099864279 and released in v7.0.0.

**Comment by sonique6784** [comment]
thanks for your work!
