### ISSUE TITLE
Wakatime shows branches of all project on each project detail view

### ISSUE THREAD

**Issue by Tuurlijk** [wakatime/jetbrains-wakatime#77]
Can the branches be shown 'per project'?

**Comment by alanhamlett** [comment]
If you click `all` then a dropdown shows the branches for that project.

<img width="316" alt="screen shot 2016-09-19 at 1 32 06 pm" src="https://cloud.githubusercontent.com/assets/522344/18630529/8b2466ca-7e6d-11e6-92a1-97a178481e9a.png">

**Comment by Tuurlijk** [comment]
This list shows branches I have had open for 'all' projects. The list shows branches from other projects too.

**Comment by alanhamlett** [comment]
This could be from #75 if your project is not being detected correctly because only branches for the current project are shown on the website. What version of the plugin are you using?

**Comment by Tuurlijk** [comment]
7.0.9

**Comment by alanhamlett** [comment]
Ok, please send me an email at support@wakatime.com and I'll check the website.

**Comment by Tuurlijk** [comment]
Don't know where I clicked before, or if you fixed something, but branches are attached to projects now.

**Comment by alanhamlett** [comment]
This bug was probably introduced when fixing #75, since we are caching the last used project and using it when unable to detect the project's name. This could cause coding activity to be mis-attributed to the wrong project if you have multiple projects open at the same time.

**Comment by alanhamlett** [comment]
This bug was probably introduced when fixing #75, since we are caching the last used project and using it when unable to detect the project's name. This could cause coding activity to be mis-attributed to the wrong project if you have multiple projects open at the same time.

Right now, the only way to prevent this is by hard-coding the project's name per directory using `.wakatime-project` files. This overwrites the project from your IDE and forces all files under that folder to use the project name from the first line of the `.wakatime-project` file.

To correctly fix this, we should retry getting the project's name until successful instead of assuming the last used project is current.

**Comment by alanhamlett** [comment]
Fixed in v9.0.0.
